export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';

export const DELETE_INVOICE = 'DELETE_TASK';
export const START_EDITING = 'START_EDITING';
export const FINISH_EDITING = 'FINISH_EDITING';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const SET_ADDNEW_ACTIVE = 'SET_ADDNEW_ACTIVE';
export const CANCEL_NEW_INVOICE = 'CANCEL_NEW_INVOICE';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_DISCOUNT = 'SELECT_DISCOUNT';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const CHANGE_INPUT_CUSTOMER_VALUE = 'CHANGE_INPUT_CUSTOMER_VALUE';
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const CUSTOMER_MODAL_SHOW = 'CUSTOMER_MODAL_SHOW';
export const CUSTOMER_MODAL_HIDE = 'CUSTOMER_MODAL_HIDE';
export const CHANGE_INPUT_PRODUCT_VALUE = 'CHANGE_INPUT_CUSTOMER_VALUE';
export const ADD_NEW_PRODUCT = 'ADD_NEW_CUSTOMER';
export const PRODUCT_MODAL_SHOW = 'PRODUCT_MODAL_SHOW';
export const PRODUCT_MODAL_HIDE = 'PRODUCT_MODAL_HIDE';

