export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const DELETE_TASK = 'DELETE_TASK';
export const START_EDITING = 'START_EDITING';
export const FINISH_EDITING = 'FINISH_EDITING';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';


